robot_type: xhand
embodiment_type: right
task: taco_brush_brush_bowl_20230927_027
dataset_dir: /data_all/zzx/3.2RL/models
dataset_name: taco_xhand
data_id: 0
model_path: /data_all/zzx/3.2RL/models/taco_xhand/xhand/right/taco_brush_brush_bowl_20230927_027/scene.xml
data_path: /data_all/zzx/3.2RL/models/taco_xhand/xhand/right/taco_brush_brush_bowl_20230927_027/0/trajectory_kinematic.npz
simulator: mjwp
device: cuda:0
sim_dt: 0.01
ctrl_dt: 0.02
ref_dt: 0.02
render_dt: 0.02
num_samples: 2
num_dyn: 1
num_dr: 1
show_viewer: false
wait_on_finish: false
use_rl_reward: false
paper_objective: true
